version: "3.9"

services:
  nfc-mqtt:
    build: .
    container_name: nfc-mqtt
    volumes:
      - "/dev/bus/usb:/dev/bus/usb"  # Give container access to NFC reader
    environment:
      MQTT_HOST: 192.168.0.123
      MQTT_PORT: 1883
      MQTT_USERNAME: tagreader
      MQTT_PASSWORD: changeme
      MQTT_TOPIC: homeassistant/nfc/tag
      LOG_LEVEL: INFO
    restart: unless-stopped
